version: '{build}'
image: Visual Studio 2017

environment:
  # Get stack traces from uno.
  LOG_TRACE: 1

install:
  - bash .fuse\install.sh
  - bash .fuse\install-android.sh
  - set PATH=.fuse;%PATH%

build_script:
  # Run build in PowerShell so we can kill java and avoid that AppVeyor hangs.
  - ps: |
    & uno build android
    $retval = $LASTEXITCODE
    & taskkill /F /IM java.exe /T
    Exit $retval

artifacts:
  - path: build\Android\Debug\app.apk

test: off
