version: '{build}'
image: Visual Studio 2017

environment:
  # Get stack traces from uno.
  LOG_TRACE: 1

install:
  - bash .fuse\install.sh
  - bash .fuse\install-android.sh
  - set PATH=.fuse;%PATH%

build_script:
  - uno create -capp -napp
  # Run Android build using Bash so we can kill Java to avoid that AppVeyor hangs,
  # and still return the right exit code from Uno.
  - bash -c "uno build android ; exitcode=$? ; taskkill //F //IM java.exe //T 2> /dev/null ; exit $exitcode"

artifacts:
  - path: build\Android\Debug\app.apk

test: off
